version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-alpine
    hostname: m2t_rabbitmq
    volumes:
      - ../conf/rabbitmq:/etc/rabbitmq
networks:
  default:
    external:
      name: m2t_net
