version: '3'
services:
  redis:
    image: redis:6-alpine
    hostname: m2t_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - m2t_redis_data:/data
      - ../conf/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '511'
volumes:
  m2t_redis_data:
    external: true
networks:
  default:
    external:
      name: m2t_net
